
version: '3.8'
services:
  gpu_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_CONFIG_FILE=/app/config/node_config.yaml
      - GPU_ALLOCATOR_MODE=decentralized
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
